name: Build and Push to Harbor
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22.15'
  IMAGE_NAME: 'portfolio-api'

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for version read)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Compute image tags
        id: meta
        run: |
          set -euo pipefail
          IMAGE="${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}"
          VERSION=$(node -p "require('./package.json').version")
          TAGS="${IMAGE}:${VERSION}\n${IMAGE}:latest"
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          {
            echo "tags<<EOF"
            printf "%b\n" "$TAGS"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
